# fly.toml app configuration file generated for d3w3r-phonebook-backend on 2024-01-27T22:53:07-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'd3w3r-phonebook-backend'
primary_region = 'bog'

[build]

[env]
  PORT = '3001'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
